version: "3.8"
services:
  node:
    image: node:12.20.0-alpine3.12
    user: node:node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - YARN_CACHE_FOLDER=/home/node/app/.cache/yarn
      - PKG_CACHE_PATH=/home/node/app/.cache/pkg
    command: tail -F anything
